on:
  push:
    branches:
      - "main"

name: "Main Branch"

# Secrets:
# * FLY_API_TOKEN - API Token for Deployment

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml
    with:
      dockerTag: "${{ github.ref_name }}"

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  deploy:
    name: "Deploy"

    needs: ['build']

    uses: ./.github/workflows/part_deploy.yml
    secrets:
      FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"