on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git remote add gigalixir $GIGALIXIR_REMOTE_URL
        env:
          GIGALIXIR_REMOTE_URL: "${{ secrets.GIGALIXIR_REMOTE_URL }}"
      - run: git push -f gigalixir HEAD:refs/heads/master
