on:
  pull_request:
    branches:
      - "*"

name: "Pull Request"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    uses: maennchen/athena/.github/workflows/part_tool_versioning.yml@main

  test:
    name: "Test"

    needs: ['detectToolVersions']

    uses: maennchen/athena/.github/workflows/part_test.yml@main
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  build:
    name: "Build"

    needs: ['detectToolVersions']

    uses: maennchen/athena/.github/workflows/part_build.yml@main
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
      nodeVersion: "${{ needs.detectToolVersions.outputs.nodeVersion }}"
      dockerBuild: false
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  dependabot:
    name: "Dependabot"

    needs: ['test', 'docs', 'build']

    uses: maennchen/athena/.github/workflows/part_dependabot.yml@main